FROM arm32v7/python:3.7-slim-buster

COPY requirements.txt ./
RUN apt-get update && apt-get install -y --no-install-recommends gcc python3-dev && \
    python3 -m pip install -r requirements.txt && \
    apt-get remove -y gcc python3-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get -y autoremove

COPY app /app
WORKDIR /app
CMD [ "python3", "-u", "./app.py" ]